@GymBuddyApi_HostAddress = http://localhost:5213

GET {{GymBuddyApi_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{GymBuddyApi_HostAddress}}/api/Auth/register
Accept: application/json
